// defines binning that is needed in the analysis
//
// all the binning is controlled by the variables in the section CONTROL VARIABLES
// -- low = lower bound
// -- high = upper bound
// -- bins = number of bins 
//    -- if bins=0, then a manually defined binning scheme is used (defined in the code
//       below)
//
// -- these bins do not define the final kinematic cuts used for the jet types; the 
//    final kinematic boundaries are set in PhiDists3.C (and additionally Diagnostics.C)
//
// Arguments:
//  - year = 12 or 13 for run12 or run13 (later figure out how to merge these)
//  - whichEtaCut = 0-all  1-large  2-small

void Bin_Splitter(Int_t year=12,
                  Int_t whichEtaCut=0)
{
  // check if valid year
  if(!(year==12 || year==13)) {
    fprintf(stderr,"ERROR: year must be 12 or 13\n");
    return;
  };


  // pi0 mass cut type (by pt or by en)
  TString mass_cut_type="en";


  // set up dependencies for specific year: relative luminosity, polarization
  TString counts_file,rtree_file,pol_file,trigid_file;
  TString fmsrootdir;
  TString masscuts_file,exclusion_list;
  switch(year) {
    case 12:
      fmsrootdir = "/home/dilks/h4/";
      counts_file = fmsrootdir+"root12fms/scalers12/counts.root";
      rtree_file = fmsrootdir+"root12fms/scalers12/rtree.root";
      pol_file = fmsrootdir+"root12fms/polar12/pol.root";
      break;
    case 13:
      fmsrootdir = "/home/dilks/h5/root12fms";
      counts_file = fmsrootdir+"scalers13/counts.root";
      rtree_file = fmsrootdir+"scalers13/rtree.root";
      pol_file = fmsrootdir+"polar13/pol.root";
      break;
  };
  masscuts_file = Form("mass_cuts_%d.dat",year);;
  exclusion_list = "exclusion_list";
  output_dir = fmsrootdir+"Output";
  redset_dir = fmsrootdir+"redset";



  ////////////////////////////////////////////////////
  //
  //    BINNING CONTROL VARIABLES
  //
  ////////////////////////////////////////////////////


  // --- azimuth
  Double_t phi_low=-3.15;
  Double_t phi_high=3.15;
  Int_t phi_bins=1;


  // --- pseudorapidity
  enum eta_case {kAll=0, kLarge, kSmall};
  Double_t eta_border = 3.28;

  Double_t eta_low=2.65; // see one_bin.root for full eta distribution
  Double_t eta_high=3.9;
  Int_t eta_bins=1;

  switch(whichEtaCut) {
    case kLarge: eta_high=eta_border; break;
    case kSmall: eta_low=eta_border; break;
  };



  // --- transverse momentum
  Double_t pt_low;  // lowest acceptable pT for runs 12 & 13; hard kin. cutoff overrides this
                            /* run 12 large: 4     small: 3.4
                             * run 13 large: 3.25  small: 2.2
                             */
  // set to run 13 values; run 12 has "hard kin. cutoff override"
  switch(whichEtaCut) {
    case kAll: pt_low=2.0; break;
    case kLarge: pt_low=3.25; break;
    case kSmall: pt_low=2.2; break;
  };
  Double_t pt_high=10.0; // pi0 reconstruction is unreliable for pT>15
  Int_t pt_bins=0;


  // --- energy
  Double_t en_low=30.0; // E>30 cutoff point for pi0s; should allow sph & thr to go lower
  Double_t en_high; // can go up to 255, but cluster merging for pi0s is problem for E>100
  switch(whichEtaCut) {
    case kAll: en_high=100; break;
    case kLarge: en_high=70; break;
    case kSmall: en_high=100; break;
  };
  Int_t en_bins=1;


  /////////////////////////////////////
  // END OF CONTROL VARIABLES SECTION
  //
  //


  // begin building env variables file
  char efile[64];
  strcpy(efile,"env_bins.sh");

  gSystem->RedirectOutput(efile,"w");
  printf("#!/bin/bash\n");
  printf("# This file was generated by Bin_Splitter.C\n");
  printf("# ** source this file while in this directory\n\n");
  printf("export SPINDIR=$(pwd)\n");

  // dependencies
  printf("\n");
  printf("export YEAR=%d\n",year);
  printf("export COUNTS_FILE=%s\n",counts_file.Data());
  printf("export RTREE_FILE=%s\n",rtree_file.Data());
  printf("export POL_FILE=%s\n",pol_file.Data());
  printf("export OUTPUT_DIR=%s\n",output_dir.Data());
  printf("export REDSET_DIR=%s\n",redset_dir.Data());
  printf("export MASSCUTS_FILE=%s\n",masscuts_file.Data());
  printf("export EXCLUSION_LIST=%s\n",exclusion_list.Data());

  // mass cut type
  printf("\nexport MASS_CUT_TYPE=%s\n",mass_cut_type.Data());


  // phi
  printf("\nexport PHI_LOW=%f\n",phi_low);
  printf("export PHI_HIGH=%f\n",phi_high);
  Double_t phi_width;
  if(phi_bins>0)
  {
    printf("export PHI_BINS=%d\n",phi_bins);
    phi_width = (phi_high-phi_low)/phi_bins;
    for(Int_t i=0; i<=phi_bins; i++) printf("export PHI_DIV_%d=%f\n",i,phi_low+i*phi_width);
  }
  else
  {
    phi_bins=1;
    printf("export PHI_BINS=%d\n",phi_bins);
    printf("export PHI_DIV_0=%f\n",phi_low);
    printf("export PHI_DIV_1=%f\n",phi_high);
  };


  // eta
  printf("\nexport ETA_LOW=%f\n",eta_low);
  printf("export ETA_HIGH=%f\n",eta_high);
  Double_t eta_width;
  if(eta_bins>0)
  {
    printf("export ETA_BINS=%d\n",eta_bins);
    eta_width = (eta_high-eta_low)/eta_bins;
    for(Int_t i=0; i<=eta_bins; i++) printf("export ETA_DIV_%d=%f\n",i,eta_low+i*eta_width);
  }
  else
  {
    eta_bins=1;
    printf("export ETA_BINS=%d\n",eta_bins);
    printf("export ETA_DIV_0=%f\n",eta_low);
    printf("export ETA_DIV_1=%f\n",eta_high);
  };


  // pt
  printf("\nexport PT_LOW=%f\n",pt_low);
  printf("export PT_HIGH=%f\n",pt_high);
  Double_t pt_width;
  if(pt_bins>0)
  {
    printf("export PT_BINS=%d\n",pt_bins);
    pt_width = (pt_high-pt_low)/pt_bins;
    for(Int_t i=0; i<=pt_bins; i++) printf("export PT_DIV_%d=%f\n",i,pt_low+i*pt_width);
  }
  else
  {
    // for en_bins=1 and eta_bins=1 -- 6 bin scheme
    ///*
    // large cells (or all cells case)
    if(whichEtaCut==kAll || whichEtaCut==kLarge)
    {
      pt_bins=3;
      printf("export PT_BINS=%d\n",pt_bins);
      printf("export PT_DIV_0=%f\n",pt_low);
      printf("export PT_DIV_1=%f\n",5);
      printf("export PT_DIV_2=%f\n",6.5);
      printf("export PT_DIV_3=%f\n",pt_high);
    }
    // small cells
    else if(whichEtaCut==kSmall)
    {
      pt_bins=3;
      printf("export PT_BINS=%d\n",pt_bins);
      printf("export PT_DIV_0=%f\n",pt_low);
      printf("export PT_DIV_1=%f\n",3.25);
      printf("export PT_DIV_2=%f\n",4);
      printf("export PT_DIV_3=%f\n",pt_high);
    };
    //*/
    // for en_bins=1 and eta_bins=1 -- 8 bin scheme
    /*
    pt_bins=8;
    printf("export PT_BINS=%d\n",pt_bins);
    printf("export PT_DIV_0=%f\n",pt_low);
    printf("export PT_DIV_1=%f\n",3);
    printf("export PT_DIV_2=%f\n",3.5);
    printf("export PT_DIV_3=%f\n",4);
    printf("export PT_DIV_4=%f\n",4.5);
    printf("export PT_DIV_5=%f\n",5.5);
    printf("export PT_DIV_6=%f\n",6.5);
    printf("export PT_DIV_7=%f\n",8);
    printf("export PT_DIV_8=%f\n",pt_high);
    */
  };

    
  // en
  printf("\nexport EN_LOW=%f\n",en_low);
  printf("export EN_HIGH=%f\n",en_high);
  Double_t en_width;
  if(en_bins>0)
  {
    printf("export EN_BINS=%d\n",en_bins);
    en_width = (en_high-en_low)/en_bins;
    for(Int_t i=0; i<=en_bins; i++) printf("export EN_DIV_%d=%f\n",i,en_low+i*en_width);
  }
  else
  {
    /*
    // for pt-dependnce for E<100 & E>100
    en_bins=2;
    printf("export EN_BINS=%d\n",en_bins);
    printf("export EN_DIV_0=%f\n",en_low);
    printf("export EN_DIV_1=%f\n",100);
    printf("export EN_DIV_2=%f\n",en_high);
    ///*
    // for pt_bins=1 and eta_bins=1
    en_bins=6;
    printf("export EN_BINS=%d\n",en_bins);
    printf("export EN_DIV_0=%f\n",en_low);
    printf("export EN_DIV_1=%f\n",25);
    printf("export EN_DIV_2=%f\n",50);
    printf("export EN_DIV_3=%f\n",75);
    printf("export EN_DIV_4=%f\n",100);
    printf("export EN_DIV_5=%f\n",150);
    printf("export EN_DIV_6=%f\n",en_high);
    */
    ///*
    en_bins=6;
    printf("export EN_BINS=%d\n",en_bins);
    printf("export EN_DIV_0=%f\n",en_low);
    printf("export EN_DIV_1=%f\n",40);
    printf("export EN_DIV_2=%f\n",50);
    printf("export EN_DIV_3=%f\n",60);
    printf("export EN_DIV_4=%f\n",70);
    printf("export EN_DIV_5=%f\n",85);
    printf("export EN_DIV_6=%f\n",en_high);
    //*/
  };
  
  
  printf("\nexport WHICH_ETA_CUT=%d\n",whichEtaCut);

  
  gSystem->RedirectOutput(0);
  char cat[128];
  sprintf(cat,".! cat %s",efile);
  printf("\n");
  gROOT->ProcessLine(cat);
  printf("\n%s built; source it by executing\n. env_bins.sh\n",efile);
};
