#!/bin/bash

if [ -z "$SPINDIR" ]; then
  echo "ERROR: source env vars first"
  exit
fi

echo "removing ${MASSSET_DIR}/*.root in 5 seconds..."
sleep 5
rm -r ${MASSSET_DIR}/*.root

job="m_inpte.bat"
> $job

echo "building batch file..."
echo "Executable = `which root`" >> $job
echo "Universe = vanilla" >> $job
echo "notification = never" >> $job
echo "getenv = True" >> $job
echo '+Experiment = "star"' >> $job
echo '+Job_Type = "cas"' >> $job
echo "" >> $job

log="logfiles"


pushd $REDSET_DIR
ls RedOutputset*.root > LIST
popd


cnt=0

while read redfile; do
  let cnt++
  echo "Arguments = -b -q MassInPTE.C(\\\"${redfile}\\\")" >> $job
  echo "Log    = ${log}/Mass.${redfile}.log" >> $job
  echo "Output = ${log}/Mass.${redfile}.out" >> $job
  echo "Error  = ${log}/Mass.${redfile}.err" >> $job
  echo "Queue" >> $job
  echo "" >> $job
done < ${REDSET_DIR}/LIST


rm ${REDSET_DIR}/LIST

echo "Submitting $cnt jobs to condor"
condor_submit $job
