#!/bin/bash
# This file was generated by Bin_Splitter.C
# ** source this file while in this directory

export SPINDIR=$(pwd)

export YEAR=12
export COUNTS_FILE=/home/dilks/h4/root12fms/scalers12/counts.root
export RTREE_FILE=/home/dilks/h4/root12fms/scalers12/rtree.root
export POL_FILE=/home/dilks/polarLUT/pol_12.root
export OUTPUT_DIR=/home/dilks/h4/Output
export REDSET_DIR=/home/dilks/h4/redset
export PHISET_DIR=/home/dilks/h4/phiset
export DIAGSET_DIR=diagset_12
export MASSSET_DIR=massset_12
export MASSCUTS_FILE=mass_cuts_12.dat
export EXCLUSION_LIST=exclusion_list

export MASS_CUT_TYPE=en

export TRIGGER_TYPE="FMSOR"

export PHI_LOW=-3.141590
export PHI_HIGH=3.141590
export PHI_BINS=1
export PHI_DIV_0=-3.141590
export PHI_DIV_1=3.141590

export ETA_LOW=2.650000
export ETA_HIGH=3.900000
export ETA_BINS=2
export ETA_DIV_0=2.650000
export ETA_DIV_1=3.130000
export ETA_DIV_2=3.900000

export PT_LOW=0.000000
export PT_HIGH=10.000000
export PT_BINS=2
export PT_DIV_0=0.000000
export PT_DIV_1=5.000000
export PT_DIV_2=10.000000

export EN_LOW=30.000000
export EN_HIGH=100.000000
export EN_BINS=2
export EN_DIV_0=30.000000
export EN_DIV_1=65.000000
export EN_DIV_2=100.000000

export WHICH_ETA_CUT=0
